const fs = require('fs');
const file = 'c:/Users/luisa/OneDrive/Desktop/wbd de lenin/matricula-virtual-unfvlenkein/base_de_datos_final.sql';
let content = fs.readFileSync(file, 'utf8');

const cursoMap = {
  '9': 'INGLES II',
  '10': 'LIDERAZGO',
  '11': 'MEDIO AMBIENTE',
  '12': 'TIC',
  '13': 'SOCIOLOGIA',
  '14': 'TEORIA DE SISTEMAS',
  '15': 'CALCULO DIFERENCIAL E INTEGRAL',
  '16': 'FUNDAMENTOS DE PROGRAMACION I',
  '17': 'INGLES III',
  '18': 'PSICOLOGA ORGANIZACIONAL',
  '19': 'ESTADSTICA',
  '20': 'GEOPOLTICA Y REALIDAD NACIONAL',
  '21': 'METODOLOGA DE LA INVESTIGACIN CIENTFICA',
  '22': 'FSICA',
  '23': 'ECUACIONES DIFERENCIALES',
  '24': 'FUNDAMENTOS DE PROGRAMACIN II',
  '25': 'PROGRAMACION APLICADA I',
  '26': 'GESTION CONTABLE',
  '27': 'ESTADISTICA II',
  '28': 'INVESTIGACION OPERATIVA',
  '29': 'ELECTROMAGNETISMO',
  '30': 'MATEMATICAS DISCRETAS',
  '31': 'PROGRAMACIN APLICADA II',
  '32': 'INGENIERA DE COSTOS Y PRESUPUESTOS',
  '33': 'FUNDAMENTOS DE BASE DE DATOS',
  '34': 'INGENIERA DE PROCESOS DE NEGOCIOS',
  '35': 'SISTEMAS DIGITALES Y ARQUITECTURA DE COMPUTADORAS',
  '36': 'SISTEMAS OPERATIVOS',
  '37': 'DINǬMICA DE SISTEMAS',
  '46': 'INGENIERA DE SOFTWARE',
  '47': 'INVESTIGACIN APLICADA',
  '48': 'ADMINISTRACIN Y GESTIN DE BASE DE DATOS',
  '49': 'PLANEAMIENTO DE RECURSOS EMPRESARIALES',
  '50': 'ARQUITECTURA Y CONECTIVIDAD DE REDES',
  '51': 'INGENIERA DEL CONOCIMIENTO',
  '52': 'SIMULACIN DE SISTEMAS',
  '54': 'TALLER DE TESIS I',
  '55': 'TALLER DE INTEGRACION DE SISTEMAS',
  '56': 'TOPICOS ESPECIALES DE IOT',
  '57': 'INTELIGENCIA DE NEGOCIOS',
  '58': 'SEGURIDAD EN REDES Y SISTEMAS DE INFORMACION',
  '59': 'INTELIGENCIA ARTIFICIAL',
  '60': 'TALLER DE TESIS II',
  '61': 'EVALUACIN DE PROYECTOS DE TI',
  '62': 'TPICOS ESPECIALES DE BIGDATA',
  '63': 'ARQUITECTURA EMPRESARIAL',
  '64': 'CIBERSEGURIDAD',
  '65': 'PRǬCTICAS PRE-PROFESIONALES I',
  '66': 'AUDITORIA DE SISTEMAS DE INFORMACION',
  '67': 'GERENCIA DE PROYECTOS DE TI',
  '68': 'FUNDAMENTOS DE BUSINESS ANALYTICS',
  '69': 'TECNOLOGIAS EMERGENTES E INNOVACION TECNOLOGICA',
  '70': 'PRACTICAS PRE-PROFESIONALES II'
};

for (let cod in cursoMap) {
  let name = cursoMap[cod];
  let searchStr = "'Curso " + cod + " Malla 2019'";
  let replaceStr = "'" + name + "'";
  content = content.replace(searchStr, replaceStr);
}

fs.writeFileSync(file, content, 'utf8');
console.log('Replaced names explicitly');
